apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-payment-service
data:
  UPLOAD_DIR: "/app/uploads"
  PUBLIC_URL: "{{ .Values.app.publicURL }}"
  WEBHOOK_URL: "{{ .Values.app.webhookURL }}"