apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-payment
  labels:
    app: mongodb-payment
spec:
  serviceName: mongodb-payment
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-payment
  template:
    metadata:
      labels:
        app: mongodb-payment
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "golunch_payments_user"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "golunch_payments_password"
            - name: MONGO_INITDB_DATABASE
              value: "golunch_payments"
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 15
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
        storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-payment
  labels:
    app: mongodb-payment
spec:
  selector:
    app: mongodb-payment
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: ClusterIP
